In [32]:
import pandas as pd
import numpy as np
import math

In [33]:
file="C:\\Users\\amtha\\Videos\\PF Assistant\\dataSet.csv"

In [34]:
df = pd.read_csv(file)
df

               Device        Type  Power(W)    PF
0         Ceiling_Fan   Inductive        75  0.70
1            LED_Bulb  Electronic        12  0.90
2        Refrigerator   Inductive       150  0.82
3     Electric_Heater   Resistive      1500  1.00
4     Air_Conditioner   Inductive      1200  0.85
5      Laptop_Charger  Electronic        65  0.95
6     Washing_Machine   Inductive       500  0.75
7   Incandescent_Lamp   Resistive        60  1.00
8      Microwave_Oven   Inductive      1100  0.88
9          Desktop_PC  Electronic       300  0.92
10         Water_Pump   Inductive       750  0.72
11         Television  Electronic       100  0.98

In [35]:
df["phase_angle_degrees"] = round(np.degrees(np.arccos(df["PF"])),3)
df["Reactive Power(VAR)"] = round(df["Power(W)"]*np.tan(np.radians(df["phase_angle_degrees"])),3)

df

,Device,Type,Power(W),PF,phase_angle_degrees,Reactive Power(VAR)
0,Ceiling_Fan,Inductive,75,0.70,45.573,76.515
1,LED_Bulb,Electronic,12,0.90,25.842,5.812
2,Refrigerator,Inductive,150,0.82,34.915,104.700
3,Electric_Heater,Resistive,1500,1.00,0.000,0.000
4,Air_Conditioner,Inductive,1200,0.85,31.788,743.684
5,Laptop_Charger,Electronic,65,0.95,18.195,21.365
6,Washing_Machine,Inductive,500,0.75,41.410,440.964
7,Incandescent_Lamp,Resistive,60,1.00,0.000,0.000
8,Microwave_Oven,Inductive,1100,0.88,28.358,593.726
9,Desktop_PC,Electronic,300,0.92,23.074,127.800
10,Water_Pump,Inductive,750,0.72,43.946,722.902
11,Television,Electronic,100,0.98,11.478,20.305

In [36]:
P_total = df["Power(W)"].sum()
Q_total = df["Reactive Power(VAR)"].sum()

S_total = math.sqrt((P_total)**2 + (Q_total)**2)

PF_total = P_total / S_total

print(
    f"P_total: {P_total:.2f} W\n",
    f"Q_total: {Q_total:.2f} VAR\n",
    f"S_total: {S_total:.2f} VA\n",
    f"PF_total: {PF_total:.2f}\n"
)

#expected PF = 0.95
#Q_c = P*(tan(theta1)-tan(theta2))
#Q_c is required reactive power

Q_c = P_total*(np.tan(np.arccos(PF_total))-np.tan(np.arccos(0.95)))

print(f"Q_c: {Q_c:.2f} VAR")

P_total: 5812.00 W
 Q_total: 2857.77 VAR
 S_total: 6476.59 VA
 PF_total: 0.90

Q_c: 947.46 VAR

In [37]:
df["Q_contribution_pct(%)"] = round((df["Reactive Power(VAR)"] / Q_total) * 100,2)
df[["Device", "Reactive Power(VAR)", "Q_contribution_pct(%)"]]

               Device  Reactive Power(VAR)  Q_contribution_pct(%)
0         Ceiling_Fan               76.515                   2.68
1            LED_Bulb                5.812                   0.20
2        Refrigerator              104.700                   3.66
3     Electric_Heater                0.000                   0.00
4     Air_Conditioner              743.684                  26.02
5      Laptop_Charger               21.365                   0.75
6     Washing_Machine              440.964                  15.43
7   Incandescent_Lamp                0.000                   0.00
8      Microwave_Oven              593.726                  20.78
9          Desktop_PC              127.800                   4.47
10         Water_Pump              722.902                  25.30
11         Television               20.305                   0.71

In [38]:
usage_prob = {
    "Ceiling_Fan": 0.6,
    "LED_Bulb": 0.8,
    "Refrigerator": 0.9, 
    "Electric_Heater": 0.2,
    "Air_Conditioner": 0.5,
    "Laptop_Charger": 0.4,
    "Washing_Machine": 0.1,
    "Incandescent_Lamp": 0.3,
    "Microwave_Oven": 0.1,
    "Desktop_PC": 0.3,
    "Water_Pump": 0.05,
    "Television": 0.4
}

In [39]:
import random

def generate_scenario(df):
    df_copy = df.copy()
    
    df_copy["ON"] = df_copy["Device"].apply(
        lambda x: 1 if random.random() < usage_prob[x] else 0
    )
    
    return df_copy

In [40]:
def compute_totals(df):
    P_total = round((df["Power(W)"] * df["ON"]).sum(),3)
    Q_total = round((df["Reactive Power(VAR)"] * df["ON"]).sum(),3)
    
    if P_total == 0:
        return 0, 0, 0
    
    S_total = round(math.sqrt(P_total**2 + Q_total**2),3)
    PF_total = round(P_total / S_total,3)
    
    return P_total, Q_total, PF_total

In [41]:
scenarios = []

for i in range(500):
    scenario_df = generate_scenario(df)
    
    P, Q, PF = compute_totals(scenario_df)
    
    # Create a dictionary for ON/OFF states
    scenario_dict = {}
    
    for _, row in scenario_df.iterrows():
        scenario_dict[row["Device"]] = row["ON"]
    
    # Add totals
    scenario_dict["P_total"] = P
    scenario_dict["Q_total"] = Q
    scenario_dict["PF_total"] = PF
    
    scenarios.append(scenario_dict)

    target_pf = 0.95

    Qc = P * (np.tan(np.arccos(PF)) - np.tan(np.arccos(target_pf)))
    scenario_dict["Q_c"] = Qc

    scenario_dict["num_devices_on"] = scenario_df["ON"].sum()

In [42]:
scenarios

[{'Ceiling_Fan': 1,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 1,
  'Air_Conditioner': 0,
  'Laptop_Charger': 0,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(1737),
  'Q_total': np.float64(187.027),
  'PF_total': np.float64(0.994),
  'Q_c': np.float64(-379.7842666844062),
  'num_devices_on': np.int64(4)},
 {'Ceiling_Fan': 0,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 1,
  'Laptop_Charger': 1,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 1,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(1487),
  'Q_total': np.float64(875.561),
  'PF_total': np.float64(0.862),
  'Q_c': np.float64(385.692914259455),
  'num_devices_on': np.int64(5)},
 {'Ceiling_Fan': 0,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 0,
  'Laptop_Charger': 0,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 1,
  'P_total': np.int64(262),
  'Q_total': np.float64(130.817),
  'PF_total': np.float64(0.895),
  'Q_c': np.float64(44.46501953987586),
  'num_devices_on': np.int64(3)},
 {'Ceiling_Fan': 1,
  'LED_Bulb': 0,
  'Refrigerator': 1,
  'Electric_Heater': 1,
  'Air_Conditioner': 1,
  'Laptop_Charger': 0,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 1,
  'Water_Pump': 0,
  'Television': 1,
  'P_total': np.int64(3325),
  'Q_total': np.float64(1073.004),
  'PF_total': np.float64(0.952),
  'Q_c': np.float64(-23.78228817715837),
  'num_devices_on': np.int64(6)},
 {'Ceiling_Fan': 0,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 0,
  'Laptop_Charger': 0,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(162),
  'Q_total': np.float64(110.512),
  'PF_total': np.float64(0.826),
  'Q_c': np.float64(57.30348832568821),
  'num_devices_on': np.int64(2)},
 {'Ceiling_Fan': 0,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 1,
  'Air_Conditioner': 1,
  'Laptop_Charger': 0,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 1,
  'P_total': np.int64(2962),
  'Q_total': np.float64(874.501),
  'PF_total': np.float64(0.959),
  'Q_c': np.float64(-98.22470049910677),
  'num_devices_on': np.int64(5)},
 {'Ceiling_Fan': 0,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 1,
  'Laptop_Charger': 1,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 1,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(1487),
  'Q_total': np.float64(875.561),
  'PF_total': np.float64(0.862),
  'Q_c': np.float64(385.692914259455),
  'num_devices_on': np.int64(5)},
 {'Ceiling_Fan': 0,
  'LED_Bulb': 1,
  'Refrigerator': 0,
  'Electric_Heater': 1,
  'Air_Conditioner': 1,
  'Laptop_Charger': 1,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 1,
  'Water_Pump': 1,
  'Television': 0,
  'P_total': np.int64(3827),
  'Q_total': np.float64(1621.563),
  'PF_total': np.float64(0.921),
  'Q_c': np.float64(360.86205902208553),
  'num_devices_on': np.int64(6)},
 {'Ceiling_Fan': 0,
  'LED_Bulb': 0,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 1,
  'Laptop_Charger': 1,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 1,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(1715),
  'Q_total': np.float64(997.549),
  'PF_total': np.float64(0.864),
  'Q_c': np.float64(435.7146872669404),
  'num_devices_on': np.int64(4)},
 {'Ceiling_Fan': 1,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 1,
  'Laptop_Charger': 0,
  'Washing_Machine': 1,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 1,
  'P_total': np.int64(2037),
  'Q_total': np.float64(1391.98),
  'PF_total': np.float64(0.826),
  'Q_c': np.float64(720.5383069100425),
  'num_devices_on': np.int64(6)},
 {'Ceiling_Fan': 1,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 0,
  'Laptop_Charger': 0,
  'Washing_Machine': 1,
  'Incandescent_Lamp': 1,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(797),
  'Q_total': np.float64(627.991),
  'PF_total': np.float64(0.785),
  'Q_c': np.float64(367.00452979003364),
  'num_devices_on': np.int64(5)},
 {'Ceiling_Fan': 0,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 1,
  'Air_Conditioner': 0,
  'Laptop_Charger': 0,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(1662),
  'Q_total': np.float64(110.512),
  'PF_total': np.float64(0.998),
  'Q_c': np.float64(-441.00089941704266),
  'num_devices_on': np.int64(3)},
 {'Ceiling_Fan': 1,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 1,
  'Laptop_Charger': 1,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 1,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(1802),
  'Q_total': np.float64(1079.876),
  'PF_total': np.float64(0.858),
  'Q_c': np.float64(486.49531507663255),
  'num_devices_on': np.int64(6)},
 {'Ceiling_Fan': 1,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 1,
  'Air_Conditioner': 0,
  'Laptop_Charger': 1,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 1,
  'Water_Pump': 0,
  'Television': 1,
  'P_total': np.int64(2202),
  'Q_total': np.float64(356.497),
  'PF_total': np.float64(0.987),
  'Q_c': np.float64(-365.19502473649777),
  'num_devices_on': np.int64(7)},
 {'Ceiling_Fan': 1,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 1,
  'Laptop_Charger': 1,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 1,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(1562),
  'Q_total': np.float64(952.076),
  'PF_total': np.float64(0.854),
  'Q_c': np.float64(438.1954677723362),
  'num_devices_on': np.int64(6)},
 {'Ceiling_Fan': 1,
  'LED_Bulb': 1,
  'Refrigerator': 0,
  'Electric_Heater': 0,
  'Air_Conditioner': 0,
  'Laptop_Charger': 0,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 1,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(1187),
  'Q_total': np.float64(676.053),
  'PF_total': np.float64(0.869),
  'Q_c': np.float64(285.7345281886444),
  'num_devices_on': np.int64(3)},
 {'Ceiling_Fan': 1,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 0,
  'Laptop_Charger': 1,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(302),
  'Q_total': np.float64(208.392),
  'PF_total': np.float64(0.823),
  'Q_c': np.float64(109.18028512454231),
  'num_devices_on': np.int64(4)},
 {'Ceiling_Fan': 0,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 0,
  'Laptop_Charger': 0,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(162),
  'Q_total': np.float64(110.512),
  'PF_total': np.float64(0.826),
  'Q_c': np.float64(57.30348832568821),
  'num_devices_on': np.int64(2)},
 {'Ceiling_Fan': 0,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 1,
  'Laptop_Charger': 1,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 1,
  'Microwave_Oven': 0,
  'Desktop_PC': 1,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(1787),
  'Q_total': np.float64(1003.361),
  'PF_total': np.float64(0.872),
  'Q_c': np.float64(415.7917283525612),
  'num_devices_on': np.int64(6)},
 {'Ceiling_Fan': 1,
  'LED_Bulb': 0,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 1,
  'Laptop_Charger': 1,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(1490),
  'Q_total': np.float64(946.264),
  'PF_total': np.float64(0.844),
  'Q_c': np.float64(457.1224473217612),
  'num_devices_on': np.int64(4)},
 {'Ceiling_Fan': 1,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 1,
  'Air_Conditioner': 1,
  'Laptop_Charger': 1,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 1,
  'P_total': np.int64(3102),
  'Q_total': np.float64(972.381),
  'PF_total': np.float64(0.954),
  'Q_c': np.float64(-44.73523615974515),
  'num_devices_on': np.int64(7)},
 {'Ceiling_Fan': 1,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 1,
  'Air_Conditioner': 0,
  'Laptop_Charger': 0,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(1737),
  'Q_total': np.float64(187.027),
  'PF_total': np.float64(0.994),
  'Q_c': np.float64(-379.7842666844062),
  'num_devices_on': np.int64(4)},
 {'Ceiling_Fan': 0,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 0,
  'Laptop_Charger': 1,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 1,
  'Water_Pump': 0,
  'Television': 1,
  'P_total': np.int64(627),
  'Q_total': np.float64(279.982),
  'PF_total': np.float64(0.913),
  'Q_c': np.float64(74.08006290449308),
  'num_devices_on': np.int64(5)},
 {'Ceiling_Fan': 0,
  'LED_Bulb': 1,
  'Refrigerator': 0,
  'Electric_Heater': 0,
  'Air_Conditioner': 0,
  'Laptop_Charger': 1,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 1,
  'P_total': np.int64(177),
  'Q_total': np.float64(47.482),
  'PF_total': np.float64(0.966),
  'Q_c': np.float64(-10.804472000588955),
  'num_devices_on': np.int64(3)},
 {'Ceiling_Fan': 1,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 0,
  'Laptop_Charger': 1,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(302),
  'Q_total': np.float64(208.392),
  'PF_total': np.float64(0.823),
  'Q_c': np.float64(109.18028512454231),
  'num_devices_on': np.int64(4)},
 {'Ceiling_Fan': 0,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 1,
  'Laptop_Charger': 1,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 1,
  'Water_Pump': 0,
  'Television': 1,
  'P_total': np.int64(1827),
  'Q_total': np.float64(1023.666),
  'PF_total': np.float64(0.872),
  'Q_c': np.float64(425.09876200342995),
  'num_devices_on': np.int64(6)},
 {'Ceiling_Fan': 1,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 1,
  'Laptop_Charger': 0,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 1,
  'Microwave_Oven': 1,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 1,
  'P_total': np.int64(2697),
  'Q_total': np.float64(1544.742),
  'PF_total': np.float64(0.868),
  'Q_c': np.float64(656.4348607031435),
  'num_devices_on': np.int64(7)},
 {'Ceiling_Fan': 1,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 1,
  'Laptop_Charger': 1,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 1,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 1,
  'P_total': np.int64(2702),
  'Q_total': np.float64(1566.107),
  'PF_total': np.float64(0.865),
  'Q_c': np.float64(679.2800184412977),
  'num_devices_on': np.int64(7)},
 {'Ceiling_Fan': 1,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 1,
  'Air_Conditioner': 0,
  'Laptop_Charger': 1,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 1,
  'Microwave_Oven': 0,
  'Desktop_PC': 1,
  'Water_Pump': 0,
  'Television': 1,
  'P_total': np.int64(2262),
  'Q_total': np.float64(356.497),
  'PF_total': np.float64(0.988),
  'Q_c': np.float64(-389.8653599906346),
  'num_devices_on': np.int64(8)},
 {'Ceiling_Fan': 1,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 1,
  'Laptop_Charger': 0,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 1,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(1737),
  'Q_total': np.float64(1058.511),
  'PF_total': np.float64(0.854),
  'Q_c': np.float64(487.2890701155877),
  'num_devices_on': np.int64(5)},
 {'Ceiling_Fan': 0,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 1,
  'Laptop_Charger': 0,
  'Washing_Machine': 1,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(1862),
  'Q_total': np.float64(1295.16),
  'PF_total': np.float64(0.821),
  'Q_c': np.float64(682.8358634145467),
  'num_devices_on': np.int64(4)},
 {'Ceiling_Fan': 0,
  'LED_Bulb': 0,
  'Refrigerator': 1,
  'Electric_Heater': 1,
  'Air_Conditioner': 0,
  'Laptop_Charger': 0,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 1,
  'P_total': np.int64(1750),
  'Q_total': np.float64(125.005),
  'PF_total': np.float64(0.997),
  'Q_c': np.float64(-439.3368900297894),
  'num_devices_on': np.int64(3)},
 {'Ceiling_Fan': 1,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 1,
  'Laptop_Charger': 1,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 1,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(1562),
  'Q_total': np.float64(952.076),
  'PF_total': np.float64(0.854),
  'Q_c': np.float64(438.1954677723362),
  'num_devices_on': np.int64(6)},
 {'Ceiling_Fan': 0,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 1,
  'Laptop_Charger': 0,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 1,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(1422),
  'Q_total': np.float64(854.196),
  'PF_total': np.float64(0.857),
  'Q_c': np.float64(387.6636314759635),
  'num_devices_on': np.int64(4)},
 {'Ceiling_Fan': 0,
  'LED_Bulb': 0,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 1,
  'Laptop_Charger': 0,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 1,
  'P_total': np.int64(1450),
  'Q_total': np.float64(868.689),
  'PF_total': np.float64(0.858),
  'Q_c': np.float64(391.46404376310613),
  'num_devices_on': np.int64(3)},
 {'Ceiling_Fan': 1,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 1,
  'Laptop_Charger': 0,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 1,
  'P_total': np.int64(1537),
  'Q_total': np.float64(951.016),
  'PF_total': np.float64(0.85),
  'Q_c': np.float64(447.35957846565543),
  'num_devices_on': np.int64(5)},
 {'Ceiling_Fan': 0,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 1,
  'Laptop_Charger': 0,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 1,
  'Television': 0,
  'P_total': np.int64(2112),
  'Q_total': np.float64(1577.098),
  'PF_total': np.float64(0.801),
  'Q_c': np.float64(884.3199191921075),
  'num_devices_on': np.int64(4)},
 {'Ceiling_Fan': 1,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 1,
  'Laptop_Charger': 0,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 1,
  'Water_Pump': 0,
  'Television': 1,
  'P_total': np.int64(1837),
  'Q_total': np.float64(1078.816),
  'PF_total': np.float64(0.862),
  'Q_c': np.float64(476.47470308985794),
  'num_devices_on': np.int64(6)},
 {'Ceiling_Fan': 1,
  'LED_Bulb': 0,
  'Refrigerator': 1,
  'Electric_Heater': 1,
  'Air_Conditioner': 0,
  'Laptop_Charger': 0,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(1725),
  'Q_total': np.float64(181.215),
  'PF_total': np.float64(0.995),
  'Q_c': np.float64(-393.830091417806),
  'num_devices_on': np.int64(3)},
 {'Ceiling_Fan': 1,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 1,
  'Laptop_Charger': 0,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 1,
  'P_total': np.int64(1537),
  'Q_total': np.float64(951.016),
  'PF_total': np.float64(0.85),
  'Q_c': np.float64(447.35957846565543),
  'num_devices_on': np.int64(5)},
 {'Ceiling_Fan': 0,
  'LED_Bulb': 0,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 0,
  'Laptop_Charger': 0,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(150),
  'Q_total': np.float64(104.7),
  'PF_total': np.float64(0.82),
  'Q_c': np.float64(55.39802828112799),
  'num_devices_on': np.int64(1)},
 {'Ceiling_Fan': 1,
  'LED_Bulb': 0,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 0,
  'Laptop_Charger': 1,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(290),
  'Q_total': np.float64(202.58),
  'PF_total': np.float64(0.82),
  'Q_c': np.float64(107.10285467684746),
  'num_devices_on': np.int64(3)},
 {'Ceiling_Fan': 0,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 0,
  'Laptop_Charger': 1,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 0,
  'P_total': np.int64(227),
  'Q_total': np.float64(131.877),
  'PF_total': np.float64(0.865),
  'Q_c': np.float64(57.067566316126786),
  'num_devices_on': np.int64(3)},
 {'Ceiling_Fan': 0,
  'LED_Bulb': 0,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 0,
  'Laptop_Charger': 0,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 1,
  'P_total': np.int64(250),
  'Q_total': np.float64(125.005),
  'PF_total': np.float64(0.894),
  'Q_c': np.float64(43.12734039481366),
  'num_devices_on': np.int64(2)},
 {'Ceiling_Fan': 0,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 0,
  'Laptop_Charger': 1,
  'Washing_Machine': 1,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 1,
  'P_total': np.int64(827),
  'Q_total': np.float64(593.146),
  'PF_total': np.float64(0.813),
  'Q_c': np.float64(320.46861192684264),
  'num_devices_on': np.int64(5)},
 {'Ceiling_Fan': 1,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 0,
  'Air_Conditioner': 0,
  'Laptop_Charger': 1,
  'Washing_Machine': 0,
  'Incandescent_Lamp': 1,
  'Microwave_Oven': 0,
  'Desktop_PC': 0,
  'Water_Pump': 0,
  'Television': 1,
  'P_total': np.int64(462),
  'Q_total': np.float64(228.697),
  'PF_total': np.float64(0.896),
  'Q_c': np.float64(77.11331333260081),
  'num_devices_on': np.int64(6)},
 {'Ceiling_Fan': 0,
  'LED_Bulb': 1,
  'Refrigerator': 1,
  'Electric_Heater': 1,
  'Air_Conditioner': 0,
  'Laptop_Charger': 1,
  'Washing_Machine': 1,
  'Incandescent_Lamp': 0,
  'Microwave_Oven': 0,
  'Desktop_PC': 1,
  'Water_Pump': 0,

In [43]:
print(generate_scenario(df))

               Device        Type  Power(W)    PF  phase_angle_degrees  \
0         Ceiling_Fan   Inductive        75  0.70               45.573
1            LED_Bulb  Electronic        12  0.90               25.842
2        Refrigerator   Inductive       150  0.82               34.915
3     Electric_Heater   Resistive      1500  1.00                0.000
4     Air_Conditioner   Inductive      1200  0.85               31.788
5      Laptop_Charger  Electronic        65  0.95               18.195
6     Washing_Machine   Inductive       500  0.75               41.410
7   Incandescent_Lamp   Resistive        60  1.00                0.000
8      Microwave_Oven   Inductive      1100  0.88               28.358
9          Desktop_PC  Electronic       300  0.92               23.074
10         Water_Pump   Inductive       750  0.72               43.946
11         Television  Electronic       100  0.98               11.478

    Reactive Power(VAR)  Q_contribution_pct(%)  ON
0                76.515                   2.68   1
1                 5.812                   0.20   1
2               104.700                   3.66   1
3                 0.000                   0.00   0
4               743.684                  26.02   0
5                21.365                   0.75   1
6               440.964                  15.43   0
7                 0.000                   0.00   1
8               593.726                  20.78   0
9               127.800                   4.47   0
10              722.902                  25.30   0
11               20.305                   0.71   1

In [44]:
dataset = pd.DataFrame(scenarios)

In [46]:
dataset.sample(30)

,Ceiling_Fan,LED_Bulb,Refrigerator,Electric_Heater,Air_Conditioner,Laptop_Charger,Washing_Machine,Incandescent_Lamp,Microwave_Oven,Desktop_PC,Water_Pump,Television,P_total,Q_total,PF_total,Q_c,num_devices_on
288,0,0,1,0,1,0,0,1,0,0,0,1,1510,868.689,0.867,371.559305,4
50,0,1,1,0,1,1,0,1,0,0,0,1,1587,895.866,0.871,373.517411,6
13,1,1,1,1,0,1,0,0,0,1,0,1,2202,356.497,0.987,-365.195025,7
126,1,0,1,0,0,0,0,0,0,0,0,0,225,181.215,0.779,107.150547,2
391,1,1,1,0,0,0,1,1,0,0,0,1,897,648.296,0.810,354.587147,6
72,1,0,1,0,1,0,0,0,0,0,0,0,1425,924.899,0.839,455.805449,3
486,0,1,1,0,1,1,0,0,1,0,0,0,2527,1469.287,0.864,642.012253,5
364,1,1,1,0,1,0,0,0,0,0,0,1,1537,951.016,0.850,447.359578,5
281,1,1,0,0,1,0,0,0,0,0,0,0,1287,826.011,0.842,401.576876,3
34,0,0,1,0,1,0,0,0,0,0,0,1,1450,868.689,0.858,391.464044,3
408,1,1,0,0,1,0,1,0,0,0,0,0,1787,1266.975,0.816,678.546831,4
0,1,1,1,1,0,0,0,0,0,0,0,0,1737,187.027,0.994,-379.784267,4
177,0,1,1,0,1,1,0,1,0,1,0,0,1787,1003.361,0.872,415.791728,6
363,1,1,0,0,1,1,0,0,0,0,0,0,1352,847.376,0.847,404.159333,4
69,1,1,1,0,0,1,0,1,0,0,0,0,362,208.392,0.867,89.075807,5
375,1,1,1,0,0,0,0,0,0,0,0,1,337,207.332,0.852,96.315125,4
97,1,1,1,0,1,1,0,0,0,1,0,0,1802,1079.876,0.858,486.495315,6
199,1,1,1,1,0,0,0,1,0,1,0,0,2097,314.827,0.989,-375.621814,6
139,0,1,1,1,0,1,0,1,1,1,0,1,3287,873.708,0.966,-200.645760,8
110,0,1,1,0,0,0,0,0,0,0,0,0,162,110.512,0.826,57.303488,2
24,1,1,1,0,0,1,0,0,0,0,0,0,302,208.392,0.823,109.180285,4
356,0,1,1,0,0,0,0,0,0,0,0,0,162,110.512,0.826,57.303488,2
47,0,1,1,0,1,0,0,0,0,0,0,0,1362,854.196,0.847,407.148678,3
443,0,1,1,0,1,0,0,0,0,1,0,0,1662,981.996,0.861,435.494073,4
169,1,1,1,0,1,0,0,0,0,0,0,0,1437,930.711,0.839,459.643810,4
257,1,1,1,0,0,0,0,1,0,1,0,1,697,335.132,0.901,106.503076,6
361,0,1,0,0,1,0,0,0,0,0,0,1,1312,769.801,0.862,340.302020,3
85,1,0,0,1,1,1,0,0,0,0,0,0,2840,841.564,0.959,-94.178984,4
305,0,1,1,0,0,0,0,1,0,1,0,1,622,258.617,0.923,54.871128,5
321,1,1,1,0,0,1,1,0,1,1,0,0,2202,1370.882,0.849,646.698198,7